### PR TITLE
Fix the build in Linux

### PR DESCRIPTION
**Pull request by eribertomota**
The first line allows anybody to build the plugin out of OBS, using headers (on Debian they are provided by the package libobs-dev).

The line 'set(CMAKE_AUTOMOC ON)' will fix the error 'undefined symbol', that breaks the plugin when loading.

### CODE REVIEW

**Comment by exeldro** [comment]
I pushed my out of tree build support change, that has conflicts with this change. Is the cmake minimum version line needed?

**Comment by eribertomota** [comment]
> I pushed my out of tree build support change, that has conflicts with this change. Is the cmake minimum version line needed?

Thanks a lot @exeldro. Without the cmake minimum version line, when building out of tree, the build stops here:


```
CMake Error at CMakeLists.txt:1 (project):
  VERSION not allowed unless CMP0048 is set to NEW

CMake Warning (dev) in CMakeLists.txt:
  No cmake_minimum_required command is present.  A line of code such as

    cmake_minimum_required(VERSION 3.22)

  should be added at the top of the file.  The version specified may be lower
  if you wish to support older CMake versions for this project.  For more
  information run "cmake --help-policy CMP0000".
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Configuring incomplete, errors occurred!
```

This is why @eaglesemanation set cmake version here[1].

[1] https://github.com/exeldro/obs-move-transition/commit/898f953a4a8da53cddc5e92e2bc458de968d8e99

Taking advantage of this message, could you introduce out of tree in obs-downstream-keyer? The package was already sent to Debian and is waiting for final approval.

**Comment by eribertomota** [comment]
To fix all things and avoid patches in Debian, I also need a find_package to find the Qt5Widgets.

```
CMake Error at CMakeLists.txt:34 (add_library):
  Target "scene-notes-dock" links to target "Qt5::Widgets" but the target was
  not found.  Perhaps a find_package() call is missing for an IMPORTED
  target, or an ALIAS target is missing?
```

**Comment by eribertomota** [comment]
For the obs-downstream-keyer, the line `find_package(Qt5Widgets)` also is needed.

**Comment by eribertomota** [comment]
Thanks!

**Pull request merged**
